export const FETCH_ACTIVITIES_BEGIN = 'FETCH_ACTIVITIES_BEGIN';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITIES_FAILURE = 'FETCH_ACTIVITIES_FAILURE';

export const SEARCH_ACTIVITY = 'SEARCH_ACTIVITY';

export const SAVE_ACTIVITIES_BEGIN = 'SAVE_ACTIVITIES_BEGIN';
export const SAVE_ACTIVITIES_SUCCESS = 'SAVE_ACTIVITIES_SUCCESS';
export const SAVE_ACTIVITIES_FAILURE = 'SAVE_ACTIVITIES_FAILURE';

export const DELETE_ACTIVITY_BEGIN = 'DELETE_ACTIVITY_BEGIN';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';
export const DELETE_ACTIVITY_FAILURE = 'DELETE_ACTIVITY_FAILURE';

export const GET_ACTIVITY_BEGIN = 'GET_ACTIVITY_BEGIN';
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS';
export const GET_ACTIVITY_FAILURE = 'GET_ACTIVITY_FAILURE';

export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_BEGIN = 'LOGOUT_BEGIN';
